### ISSUE TITLE
Localeを消すとたまにアプリがシャットダウンする

### ISSUE THREAD

**Issue by Saayaman** [globaltimer/Android-App#49]
Current Local であっても、ない時もどちらもありうる。

**Comment by HoNKoT** [comment]
```
CompareLocale{id=9, basis=false, gmtId='America/Phoenix', taskName='', locationName='Arizona', zonedDateTime=2017-03-06T19:11-07:00[GMT-07:00]}
FATAL EXCEPTION: main
Process: honkot.gscheduler, PID: 14260
com.github.gfx.android.orma.exception.NoValueException: Expected single get for 1 but nothing for CompareLocale
    at com.github.gfx.android.orma.Selector.get(Selector.java:251)
    at honkot.gscheduler.utils.MyRecAdapter.getItemForPosition(MyRecAdapter.java:146)
    at honkot.gscheduler.fragment.RecordListFragment$2.onItemClicked(RecordListFragment.java:133)
    at honkot.gscheduler.utils.MyRecAdapter$MyViewHolder.onClick(MyRecAdapter.java:107)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21153)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by HoNKoT** [comment]
Editのとき連続削除すると、positionがおかしい値で削除しようとしてるから死ぬ
