### ISSUE TITLE
TimeZoneが未対応だったら落ちちゃう

### ISSUE THREAD

**Issue by HoNKoT** [globaltimer/Android-App#72]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.lovesalmon.globalclock/jp.lovesalmon.globalclock.activity.TabActivity}: org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: JST
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: JST
	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:178)
	at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:133)
	at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
	at org.threeten.bp.ZoneId.of(ZoneId.java:357)
	at jp.lovesalmon.globalclock.model.CompareLocale.<init>(CompareLocale.java:56)
	at jp.lovesalmon.globalclock.activity.TabActivity.setDefaultLocale(TabActivity.java:213)
	at jp.lovesalmon.globalclock.activity.TabActivity.onCreate(TabActivity.java:61)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more
```

**Comment by HoNKoT** [comment]
これ明日そっこうで対応してbugfixリリースする
初回起動で落ちてるのは痛すぎる
