### ISSUE TITLE
daoが見つかってない？

### ISSUE THREAD

**Issue by HoNKoT** [globaltimer/Android-App#73]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.lovesalmon.globalclock/jp.lovesalmon.globalclock.activity.TabActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'jp.lovesalmon.globalclock.model.CompareLocale jp.lovesalmon.globalclock.dao.CompareLocaleDao.getBasisLocale()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'jp.lovesalmon.globalclock.model.CompareLocale jp.lovesalmon.globalclock.dao.CompareLocaleDao.getBasisLocale()' on a null object reference
	at jp.lovesalmon.globalclock.fragment.CompareListFragment.initialize(CompareListFragment.java:66)
	at jp.lovesalmon.globalclock.activity.TabActivity.onPageSelected(TabActivity.java:172)
	at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1967)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:664)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
	at android.support.v4.view.ViewPager.onRestoreInstanceState(ViewPager.java:1482)
	at android.view.View.dispatchRestoreInstanceState(View.java:15751)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3231)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3237)
	at android.view.View.restoreHierarchyState(View.java:15729)
	at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2106)
	at android.app.Activity.onRestoreInstanceState(Activity.java:1047)
	at android.app.Activity.performRestoreInstanceState(Activity.java:1002)
	at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1174)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2638)
	... 9 more
```

**Comment by HoNKoT** [comment]
バグ祭りだわっしょいわっしょい

たぶんinjectがうまくいってない？
よくわからないバグ。。

**Comment by HoNKoT** [comment]
再発報告があがるまではとりあえず放っておこう。。

**Comment by HoNKoT** [comment]
再発しとる（笑）

```
java.lang.NullPointerException: Attempt to invoke virtual method 'jp.lovesalmon.globalclock.model.CompareLocale jp.lovesalmon.globalclock.dao.CompareLocaleDao.getBasisLocale()' on a null object reference
	at jp.lovesalmon.globalclock.fragment.CompareListFragment.initialize(CompareListFragment.java:66)
	at jp.lovesalmon.globalclock.activity.TabActivity.onPageSelected(TabActivity.java:172)
	at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1967)
	at android.support.v4.view.ViewPager.scrollToItem(ViewPager.java:685)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:669)
	at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
	at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
	at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2178)
	at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1155)
	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1148)
	at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1118)
	at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1413)
	at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1523)
	at android.view.View$PerformClick.run(View.java:22429)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```
